stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: registry.gitlab.com/SEU_USUARIO/meu-app:latest
  KUBE_CONTEXT: "kubernetes"  # Ajuste conforme necess치rio
  KUBE_NAMESPACE: "default"     # Ajuste conforme necess치rio

build:
  stage: build
  image: docker:latest
  services:
    - docker:19.03.12-dind
  script:
    - docker build -t $DOCKER_IMAGE .
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
    - docker push $DOCKER_IMAGE
  only:
    - main  # Altere conforme necess치rio

deploy:
  stage: deploy
  image: bitnami/kubectl:latest
  script:
    - kubectl config use-context $KUBE_CONTEXT
    - kubectl apply -f deployment.yaml
    - kubectl rollout status deployment/meu-app
  only:
    - main  # Altere conforme necess치rio
